config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :basketball_teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basketball_team.rb
class BasketballTeam < ApplicationRecord
    has_many :players, dependent: :destroy
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :basketball_team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/basketball_teams_controller.rb
class BasketballTeamsController < ApplicationController
    before_action :find_team, only: [:show, :edit, :update, :destroy]
    def index
        @teams = BasketballTeam.all 
    end

    def show  
    end

    def new
        @team = BasketballTeam.new
    end 

    def create
        @team = BasketballTeam.create(team_params)
        redirect_to basketball_team_path(@team)
    end

    def edit
    end

    def update
        @team.update(team_params)
        redirect_to basketball_team_path(@team)
    end 

    def destroy
        @team.destroy
        redirect_to basketball_teams_path
    end

    private #make sure private is downcased

    def find_team
        @team = BasketballTeam.find(params[:id])
    end

    def team_params
        params.require(:basketball_team).permit(:city_name, :team_name, :team_colors, :no_of_championships)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :find_player, only: [:show, :edit, :update]
    before_action :find_teams, only: [:new, :edit]
    def index
        @players = Player.all
    end

    def show
    end

    def new
        @player = Player.new
    end

    def create
        @player = Player.create(player_params)
        redirect_to player_path(@player)
    end
    
    def edit
    end

    def update
        @player.update(player_params)
        redirect_to player_path(@player)
    end

    def destroy
        Player.destroy(params[:id])
        redirect_to players_path
    end

    private

    def find_teams
        @teams = BasketballTeam.all
    end

    def find_player
        @player = Player.find(params[:id])
    end

    def player_params
        params.require(:player).permit(:name, :number, :basketball_team_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basketball_teams_helper.rb
module BasketballTeamsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/basketball_teams/edit.html.erb
<h2> Edit: <%= @team.team_name %> </h2>


<%= form_for @team do |f|%>
    <%= f.label :city_name, "City Name" %>
    <%= f.text_field :city_name %><br>
    <%= f.label :team_name, "Team Name" %>
    <%= f.text_field :team_name %><br>
    <%= f.label :team_colors, "Team Colors" %>
    <%= f.text_field :team_colors %><br>
    <%= f.label :no_of_championships, "Championships" %>
    <%= f.number_field :no_of_championships, min: 0,  step: 1 %><br>
    <%= f.submit "Submit Team" %>
    <% end %>

app/views/basketball_teams/index.html.erb
<h1>Basketball Teams</h1>

<ul>
<% @teams.each do |t| %>
    <li><%= link_to t.team_name, basketball_team_path(t) %></li>
    <% end %>
 </ul>

 <h5><%= link_to "Add Team", new_basketball_team_path %></h5>

 <h5><%= link_to "All Players", players_path %></h5>
    

app/views/basketball_teams/new.html.erb
<h3> Add New Team </h3>

<%= form_for @team do |f|%>
    <%= f.label :city_name, "City Name" %>
    <%= f.text_field :city_name %><br>
    <%= f.label :team_name, "Team Name" %>
    <%= f.text_field :team_name %><br>
    <%= f.label :team_colors, "Team Colors" %>
    <%= f.text_field :team_colors %><br>
    <%= f.label :no_of_championships, "Championships" %>
    <%= f.number_field :no_of_championships, min: 0,  step: 1 %><br>
    <%= f.submit "Submit Team" %>
    <% end %>
    

app/views/basketball_teams/show.html.erb
<h1><%= @team.team_name %> </h1>

<ul>
    <li>City: <%= @team.city_name %> </li>
    <li>Team Colors: <%= @team.team_colors %> </li>
    <li>Championships: <%= @team.no_of_championships %> </li>
    <li>Players:
        <ul>
            <% @team.players.each do |player| %>
                <li><%= link_to player.name, player_path(player) %></li>
                <% end %>
        </ul>
    </li> 

</ul>


<h5><%= link_to "Main Page", basketball_teams_path%></h5>
<h5><%= link_to "Edit Team", edit_basketball_team_path%></h5>
<h5><%= link_to "Add Player", new_player_path %></h5>
<h5><%= link_to "Delete Team", basketball_team_path, method: :delete, data: {confirm: "Are you sure you want to delete this?"}%></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasketballTeams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<h1><%= "Edit" + " #{@player.name}"%></h1>

<%= form_for @player do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :number %>
    <%= f.number_field :number%><br>
    <%= f.label :basketball_team_id, "Basketball Team:"%>
    <%= f.select :basketball_team_id, options_for_select(@teams.collect { | team | [team.team_name, team.id] })%><br>
    <%= f.submit "Update Player" %>
    <% end %>

app/views/players/index.html.erb
<h1> All Players </h1>

<ul>
    <% @players.each do |player| %>
        <li><%= link_to player.name , player_path(player) %></li>
        <%end %>
</ul>

<h3><%= link_to "All Basketball Teams", basketball_teams_path %></h3>

app/views/players/new.html.erb
<h1>Add Player</h1>

<%= form_for @player do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :number %>
    <%= f.number_field :number%><br>
    <%= f.label :basketball_team_id, "Basketball Team:"%>
    <%= f.select :basketball_team_id, options_for_select(@teams.collect { | team | [team.team_name, team.id] })%><br>
    <%= f.submit "Add Player" %>
    <% end %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<ul>
    <li>Number: <%= @player.number%></li>
    <li>Team: <%= link_to(@player.basketball_team.city_name + " " + @player.basketball_team.team_name, basketball_team_path(@player.basketball_team))%></li>
</ul>

<h5><%= link_to "Edit Player", edit_player_path(@player)%></h5>
<h5><%= link_to "Delete Player", player_path(@player), method: :delete, data: {confirm: "Are you sure you want to delete this?"}%></h5>